# File: .github/workflows/deploy.yml
name: nextjs-frontend - Deploy to AWS EC2 (Dev Mode)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy nextjs-frontend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "."
          target: "~/trucker-admin-frontend"

      - name: SSH & Deploy node-express-backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/trucker-admin-frontend
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            npm install --legacy-peer-deps

            # Skip .env injection â€” you manage it manually

            # Restart the app with PM2 using npm run dev
            pm2 delete trucker-backend || true
            pm2 start npm --name trucker-backend -- run dev
